"""Shared LLM tier label handling for GitHub issue automation scripts.

cicaid's AI-suggested issues are tagged with a "tier" label that names
the model best suited to implement them: ``haiku``, ``sonnet``, or ``opus``
(roughly ordered from "simple, mechanical" to "complex, architectural").
Issue bodies generated by AI review tooling include a "**LLM tier**" section
naming one of these tiers; this module finds that tier and maps it to the
corresponding GitHub label.

This module is stdlib-only so it can be imported by any script under
``.github/scripts`` (or other workflow tooling) without extra dependencies.
"""

from __future__ import annotations
import logging


logger = logging.getLogger(__name__)
import re

# Maps a recognised tier name to its GitHub label. Keys are matched
# case-insensitively against issue bodies and model name strings.
LLM_TIER_MAP: dict[str, str] = {
    "haiku": "haiku",
    "sonnet": "sonnet",
    "opus": "opus",
}

# Tier label used by get_fallback_tier_label() when a model string doesn't
# name any known tier. Sonnet is the mid-point of the tier scale, so it's the
# safest default when no signal is available.
_DEFAULT_TIER_LABEL = "sonnet"


def _build_tier_pattern(tier_map: dict[str, str]) -> re.Pattern[str]:
    """Build a regex matching a "**LLM tier**" section naming one of tier_map's keys."""
    tiers = "|".join(re.escape(tier) for tier in tier_map)
    return re.compile(
        rf"\*\*LLM\s+tier\*\*[^\n]*\n[^\n]*\*\*({tiers})\b",
        re.IGNORECASE,
    )


def extract_tier_label(body: str, tier_map: dict[str, str] | None = None) -> str | None:
    """Return the tier label named in ``body``, or None if no tier is mentioned.

    Looks first for a "**LLM tier**" section naming a known tier, then falls
    back to a bare mention of a tier name anywhere in the body.
    """
    tier_map = LLM_TIER_MAP if tier_map is None else tier_map
    pattern = _build_tier_pattern(tier_map)
    m = pattern.search(body)
    if m:
        return tier_map.get(m.group(1).lower())
    for tier, label in tier_map.items():
        if re.search(rf"\b{re.escape(tier)}\b", body, re.IGNORECASE):
            return label
    return None


def get_fallback_tier_label(model_name: str, tier_map: dict[str, str] | None = None) -> str:
    """Derive a tier label from a model name string (e.g. "claude-haiku-4-5-20251001").

    Used when a tier can't be extracted from issue body text but a model name
    is available. Returns ``_DEFAULT_TIER_LABEL`` if the model name doesn't
    name a known tier.
    """
    tier_map = LLM_TIER_MAP if tier_map is None else tier_map
    model_lower = model_name.lower()
    for tier, label in tier_map.items():
        if tier in model_lower:
            return label
    return _DEFAULT_TIER_LABEL
