"""CLI tool to review uncommitted local changes using a local or cloud LLM.

Compares the current working directory (including uncommitted changes)
against the target branch (default: main) and generates a markdown report
with the review from the chosen model (local Ollama or cloud DeepSeek, via
lib/llm_common.py).
"""

from __future__ import annotations

import argparse
import datetime
import logging
import os
import subprocess
import sys
from argparse import Namespace
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")

# Add this script's own dir (for the sibling d_work_on_issue module) and the
# local lib/ dir (for llm_common, review_common, publish_pr, github_repo) to
# sys.path so this works both as an importable module and when invoked
# directly (e.g. `python i_local_review.py`), where the package root is not
# on sys.path.
sys.path.insert(0, str(Path(__file__).parent))
sys.path.insert(0, str(Path(__file__).parent / "lib"))
from llm_common import (  # noqa: E402
    add_model_source_arg,
    describe_model_source,
    fetch_review,
    validate_model_source,
)
from review_common import (  # noqa: E402
    build_prompt,
    finalize_review,
    truncate_diff
)
from publish_pr import extract_issue_id, get_current_branch  # noqa: E402

from d_work_on_issue import fetch_issue  # noqa: E402
from github_repo import get_repo_info  # noqa: E402

def get_git_root() -> str:
    """Get the root directory of the git repository."""
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            capture_output=True,
            text=True,
            encoding="utf-8",
            check=True,
        )
        return result.stdout.strip()
    except subprocess.CalledProcessError as exc:
        logger.error(f"ERROR: Not a git repository or git command failed: {exc}")
        raise SystemExit(1) from exc

def get_local_diff(target_branch: str = "main") -> str:
    """Get diff of uncommitted changes against target branch.

    Includes:
    1. Changes staged for commit
    2. Unstaged changes in tracked files
    3. Summary of untracked files (without content to avoid noise)
    """
    try:
        # Get the diff against the target branch (commits + uncommitted changes)
        result = subprocess.run(
            ["git", "diff", f"{target_branch}...HEAD"],
            capture_output=True,
            text=True,
            encoding="utf-8",
            check=True,
        )
        diff = result.stdout

        # Also include any uncommitted changes in the working tree
        result = subprocess.run(
            ["git", "diff", "HEAD"],
            capture_output=True,
            text=True,
            encoding="utf-8",
            check=True,
        )
        if result.stdout:
            diff += "\n" + result.stdout

        # Note untracked files
        result = subprocess.run(
            ["git", "ls-files", "--others", "--exclude-standard"],
            capture_output=True,
            text=True,
            encoding="utf-8",
            check=True,
        )
        untracked = result.stdout.strip()
        if untracked:
            untracked_list = "\n".join(f"  {line}" for line in untracked.splitlines())
            diff += f"\n\n# Untracked files (not included in diff):\n{untracked_list}\n"

        return diff
    except subprocess.CalledProcessError as exc:
        logger.error(f"ERROR: Failed to generate diff: {exc}")
        raise SystemExit(1) from exc


def generate_markdown_report(
    review: str,
    target_branch: str,
    current_branch: str,
    model: str,
    diff_size: int,
    timestamp: str,
) -> str:
    """Generate a markdown report with review results."""
    return f"""# Local Code Review Report

**Generated:** {timestamp}

## Context

- **Current branch:** {current_branch}
- **Compared against:** {target_branch}
- **AI Model:** {model}
- **Diff size:** {diff_size} characters

## Review

{review}

---
*Generated by `scripts/dev_tools/local_review.py`*
"""


def save_report(content: str, output_path: str) -> str:
    """Save markdown report to file. Return the absolute path."""
    output_file = Path(output_path)
    output_file.parent.mkdir(parents=True, exist_ok=True)
    output_file.write_text(content, encoding="utf-8")
    return str(output_file.absolute())


def main() -> int:
    """Run the local review flow."""
    args = add_arguments()

    if not validate_model_source(args.model_source):
        return 1

    current_branch = get_current_branch()

    # Get local diff
    diff = get_diff(args, current_branch)

    if not diff.strip():
        logger.error("No changes found to review.")
        return 0

    # Get repo info
    try:
        owner, repo = get_repo_info()
    except ValueError as exc:
        logger.error(f"Error: {exc}")
        sys.exit(1)
        
    # Build prompt and fetch review
    token = os.getenv("GITHUB_TOKEN")
    issue_id =extract_issue_id(current_branch)
    issue_body = fetch_issue(owner, repo, issue_id, token)

    logger.info(f"INFO: Using {describe_model_source(args.model_source)}")
    prompt = build_prompt(
        pr_title=f"Local changes on {current_branch}",
        diff=diff,
        issue_body=issue_body,
        discussion="",
        verified_facts="",
    )
    review = fetch_review(args.model_source, prompt)

    if not review.strip():
        logger.error("ERROR: Model returned an empty review")
        return 1

    # Generate timestamp for report
    timestamp = datetime.datetime.now(datetime.UTC).isoformat()

    # Generate markdown report
    report = generate_markdown_report(
        review=review,
        target_branch=args.branch,
        current_branch=current_branch,
        model=describe_model_source(args.model_source),
        diff_size=len(diff),
        timestamp=timestamp,
    )

    # Output or save report
    if args.output:
        return save_review_to_file(args, review)
    else:
        return finalize_review(review, "ERROR: Model returned an empty review")


def get_diff(args: Namespace, current_branch: str) -> Any:
    logger.info(f"INFO: Comparing {current_branch} against {args.branch}...")
    diff = get_local_diff(args.branch)

    # Truncate diff if needed
    original_diff_len = len(diff)
    diff, was_truncated = truncate_diff(diff)
    if was_truncated:
        logger.info(
            "Truncated diff from %s to %s characters",
            original_diff_len,
            len(diff),
        )
    return diff


def add_arguments() -> Namespace:
    parser = argparse.ArgumentParser(
        description="Review uncommitted local changes using a local or cloud LLM "
                    "and generate a markdown report"
    )
    parser.add_argument(
        "--branch",
        default="main",
        help="Target branch to compare against (default: main)",
    )
    parser.add_argument(
        "--output",
        "-o",
        help="Output markdown file path (default: local_review_<timestamp>.md)",
    )
    add_model_source_arg(parser)
    args = parser.parse_args()
    return args


def save_review_to_file(args: Namespace, report: str) -> int:
    # Determine output file path
    if args.output:
        output_path = args.output
    else:
        # Generate default filename with timestamp
        ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        output_path = f"local_review_{ts}.md"

    try:
        abs_path = save_report(report, output_path)
        logger.info(f"Review saved to: {abs_path}")
        return 0
    except OSError as exc:
        logger.error(f"ERROR: Failed to save report: {exc}")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
